from . import mirakl_binding
from . import mirakl_importer
from . import mirakl_sale_order_importer
from . import product_template_sale_channel_rel
from . import product_template
from . import product_product
from . import res_partner
from . import sale_channel
from . import sale_channel_mirakl
from . import sale_channel_owner
from . import sale_order
