from . import mirakl_binding
from . import sale_channel_owner
from . import mirakl_importer
from . import mirakl_res_partner_importer
from . import mirakl_customer_importer
from . import mirakl_sale_order_importer
from . import product_template
from . import product_product
from . import res_partner_sale_channel_rel
from . import res_partner
from . import sale_channel
from . import sale_channel_mirakl
from . import mirakl_sale_order_line_importer
from . import sale_order
from . import product_pricelist
