[project]
name = "odoo-addons-oca-sale-channel"
version = "18.0.20260518.0"
dependencies = [
    "odoo-addon-sale_channel==18.0.*",
    "odoo-addon-sale_channel_category==18.0.*",
    "odoo-addon-sale_channel_partner==18.0.*",
    "odoo-addon-sale_channel_product==18.0.*",
    "odoo-addon-sale_channel_search_engine==18.0.*",
]
classifiers=[
    "Programming Language :: Python",
    "Framework :: Odoo",
    "Framework :: Odoo :: 18.0",
]
